language: node_js
node_js:
  - "4.5"
dist: trusty
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - STAGING_BRANCH=develop
  - secure: CopIliyM3lwf1eZe2V7CtSLojETwDV7hs0lwZIx4rlJvMPqs+N2LPDC1NDqw8mU9/4lIYzMbAN7v/H9wn0jdr8T0KI06ErZkVOxOyidGxKg5k1cMaXP3AIvo2lsWlSwm67L78WuRzQ0oFJ1cMLM4sJx6s7Z6sAO3/nymcar4nhw=
addons:
  chrome: stable
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/build.sh
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- npm run lint
- npm test
script:
- ".build_scripts/build.sh"
deploy:
  - provider: script
    skip_cleanup: true
    script: ".build_scripts/deploy.sh"
    on:
      branch: "${DEPLOY_BRANCH}"
  - provider: s3
    access_key_id: AKIAICOK2OJWL55JOBCQ
    secret_access_key:
      secure: N7qWGI64runhndCuScA3MCBGiCWR2gwCfEt+dZukfw5DL77Q7feBXcKwvUQ21KCM1FHHQUIedL0aps/jJOQHby06Iwe2sGvtkT9qWhWudbHtOi4FcG1hMNrcIZlSjrB/GQ0hFCnJDpqc+ztgTMKHVXDTmb+8TmIqEtqb19/2sCI=
    bucket: imagery-coordination-staging
    region: us-east-1
    local-dir: dist
    skip_cleanup: true
    acl: public_read
    on:
      repo: hotosm/imagery-coordination
      branch: "${STAGING_BRANCH}"
