language: node_js
node_js:
  - "4.5"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=develop
  - secure: "cJOLHRIF57ZmdQlKnx/CTXEFP0wn4lqzzqIn5FlebdGRTM3LhTtfuSdkZqIsJE1avIdIzezhbpS29VMCNKxniuvg7CsUgWa0hrqSKFgOsHXO+Ax1m04TKuJVd9YVZGzNiL+bY3wuU7TRULOOk+G1fBKyZyfc/lqGqSo8Kn2WNO8=" # GH_TOKEN

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh

before_script:
- npm run lint
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
